<?php $this->headTitle()->append('Frequently Asked Questions'); 
$this->headMeta()->appendName('description', 'Answers to the most frequently asked questions at this money making site.'); 
$this->headMeta()->appendName('keywords', 'frequently asked questions'); ?>

<h1>Frequently Asked Questions</h1>

<ul>

	<li class="lispacer"><a href="#" name="faq-1">Is their a sign up bonus when you join?</a>
	<div class="faq-answer" id="faq-1"><br />
	
	Yes, there is a $5.00 sign up bonus for joining.
	
	<br /><br /></div></li>
	<li class="lispacer"><a href="#" name="faq-2">When do you pay commissions earned?</a>

	<div class="faq-answer" id="faq-2"><br />
	
	Commissions are paid out after you have earned the minimum balance of $25.00 on the first of the upcoming month.
	
	<br /><br /></div></li>
	<li class="lispacer"><a href="#" name="faq-3">How much can I make?</a>
	
	<div class="faq-answer" id="faq-3"><br />
	
	How much you earn is entirely up to you in your efforts to refer others and complete paid offers.
	
	<br /><br /></div></li>
		
</ul>	