<?php $this->headTitle()->append('Make money today!'); 
$this->headMeta()->appendName('description', 'Join this site to increase your income today.'); 
$this->headMeta()->appendName('keywords', 'register, new account'); 

 if ($this->escape($this->submitted)) { ?>
<h2>Thank you for your Registration to the Money Making website</h2>
<p>Please check your email and click on the link to activate your account.</p>
<?php } else { ?>

<p>Join today and reap the benefits of the sign up bonuses!</p>

<p>ref page - You were referred by <?php echo $this->escape($this->refid); ?></p>

<fieldset>
<legend>Register</legend>
<?php echo $this->form; ?>
</fieldset>
<?php } ?>
