<?php $this->headTitle()->append('Speed up your earnings and register for an account');
      $this->headMeta()->appendName('description', 'Register for an account with the sign up bonus downline builder.'); 
	  $this->headMeta()->appendName('keywords', 'register, new account'); 
	
 if ($this->escape($this->submitted)) { ?>
<h2>Thank you for your Registration to the Money Making website</h2>
<p>Please check your email and click on the link to activate your account.</p>
<?php } else { ?>

<!--
<p><fb:registration fields="[
 {'name':'first_name', 'description':'First Name:', 'type':'text'},
 {'name':'last_name', 'description':'Last Name:', 'type':'text'},
 {'name':'username', 'description':'Username:', 'type':'text'},
 {'name':'email'},
 {'name':'password'},
 {'name':'terms',       'description':'I agree to the Terms', 'type':'checkbox',  'default':'checked'},
 {'name':'captcha'}
]" client_id="223751357754052" redirect-uri="http://paidtosignup/register"></fb:registration></p> -->


<fieldset>
<legend>Register</legend>
<?php echo $this->form; ?>
<p><?php if ($this->escape($this->refusername) == 'admin') { echo ''; } else { echo 'You were referred by: <b>' . $this->escape($this->refusername) . '</b>'; } ?></p>
</fieldset>
<?php } ?>
