<?php

/*
* Author: Greg London
* http://greglondon.info
*/

?>

<div class="submit_area">

     <?php echo $this->formText('message', 'empty', array('size' => 32, 'id' => 'message')) ?>

     <?php echo $this->formSubmit('submitTo', 'submit', array('id' => 'submitTo')) ?>

     

     <div class="show-msg"></div>

</div>
 

<script type="text/javascript">
    $(document).ready(function(){
            
            $("#submitTo").click(function(){
                  var message = $('#message').val();
                  if (message != '') {
                      
                      $.post('index/ajax', 
                                {'message' : message}, 
                                
                   
                                function (respond) {
                                   
                                     $(".show-msg").html(respond);                  

                        		 }
					  		);
                  }                    
            });
      });
</script>
