<?php $this->headTitle()->append('Banners & Referral links'); 
$this->headMeta()->appendName('description', 'Get banners and other affiliate link to promote this Money Making site.'); 
$this->headMeta()->appendName('keywords', 'banners, affiliate links, promote'); ?>

<h1>Banners & affiliate links</h1>

<p>Easily promote this money making site with the banners, text, and pre-written emails below.</p>