<?php $this->headTitle()->append('Downline Builder'); 
$this->headMeta()->appendName('description', 'Sign up bonus sites and add your own custom links'); 
$this->headMeta()->appendName('keywords', 'sign up bonus, sites, custom links'); 
if ($this->escape($this->submitted)) { ?>
<h1>Your Downline Builder has been updated</h1>

<?php } elseif ($this->escape($this->customSubmit)) { ?>

<h1>Your Custom Link has been updated</h1>

<?php } else { ?>

<ul>

<li class="lispacer"><a href="#" name="faq-1">Update your builder</a>
<div class="faq-answer" id="faq-1"><br />

<fieldset>
<legend>Downline Builder</legend>
<?php echo $this->form; ?>
</fieldset>

<br /><br /></div></li>

<li class="lispacer"><a href="#" name="faq-2">Update your 1st custom link</a>
<div class="faq-answer" id="faq-2"><br />

<fieldset>
<legend>Custom Link #1</legend>
<?php echo $this->custom; ?>
</fieldset>

<br /><br /></div></li>

<?php if ($this->customError2) { ?>
<fieldset>
<legend>Custom Link #2</legend>
<?php echo $this->custom2; ?>
</fieldset>
<?php } else { ?>
<li class="lispacer"><a href="#" name="faq-3">Update your 2nd custom link</a>
<div class="faq-answer" id="faq-3"><br />

<fieldset>
<legend>Custom Link #2</legend>
<?php echo $this->custom2; ?>
</fieldset>

<br /><br /></div></li>
<?php } ?>

<li class="lispacer"><a href="#" name="faq-4">Update your 3rd custom link</a>
<div class="faq-answer" id="faq-4"><br />

<fieldset>
<legend>Custom Link #3</legend>
<?php echo $this->custom3; ?>
</fieldset>

<br /><br /></div></li>

</ul>

<?php } ?>