<?php 

/*
* Author: Greg London
* http://greglondon.info
*/

$this->headTitle()->append('Upgrade your membership'); 
$this->headMeta()->appendName('description', 'Upgrade to get the full benefits of this Money Making site.'); 
$this->headMeta()->appendName('keywords', 'upgrade'); 

?>

<h1>Upgrade your membership</h1>

<p>You know you want to.</p>

<ul>
<li class="lispacer">Benefit 1</li>
<li class="lispacer">Benefit 2</li>
<li class="lispacer">Benefit 3</li>
</ul>